sudo: required

services: 
    - docker

before_install:
    - docker build -t abdulayubzoi/docker-react -f dockerfile.dev .

script:
    - docker run abdulayubzoi/docker-react npm run test -- --coverage